### ISSUE TITLE
Eloquent Magic where* methods and *_count properties

### ISSUE THREAD

**Issue by plweil** [laravel-idea/plugin#166] opened 2020-12-03 15:14 UTC
I'm just switching over from using the [old Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper), and I've noticed a couple of things that I'll try to make into separate issues.

The old Helper generates magic where* methods and *_count properties, and adds in an Eloquent @mixin tag to the phpdocs. With this plugin, PHPStorm does not recognize these methods as valid unless I add them manually to the model; e.g., 

      /**
     * Class Alumnus
     * @package App\Models     
     * @method static \Illuminate\Database\Eloquent\Builder|Alumnus whereId($value)
     * @method static \Illuminate\Database\Eloquent\Builder|Alumnus whereSenateDistrictId($value)
     * @method static \Illuminate\Database\Eloquent\Builder|Alumnus whereYearId($value)
     [...]
     * @mixin \Illuminate\Database\Eloquent\Builder
     */

Adding this @mixin tag also seems to be the only way to enable PHPStorm to recognize all of the methods in places like

    Illuminate\Database\Eloquent\Concerns\QueriesRelationships
    Illuminate\Database\Query\Builder

I confess that I don't have the most complete understanding of how all of this works, but can this capability be added, or is it already there and I don't see it (or am I doing something wrong)? Thanks!

**Comment by adelf** [comment] 2020-12-03 15:17
As I saw in the previous issue, you chose dynamic query methods style in the generation window. You can choose static. Also I’m going to remove this option and generate helper code for both styles. So, please, don’t close this issue.

**Comment by plweil** [comment] 2020-12-03 15:42
Thanks @adelf. I'm not quite sure I understand what each option does, but if both styles are generated, and one of them resolves the issue, then that's all I need.

Perhaps this is a related issue, but I have a couple of local query scopes that are shared among models via a trait. If I add

     * @mixin \Illuminate\Database\Eloquent\Builder

PHPStorm complains "Method [name] not found in [modelName]". If I remove the @mixin tag, PHP doesn't complain about the scope; but then it complains about Eloquent Builder methods.

**Comment by adelf** [comment] 2020-12-03 15:50
Could you try to run generator with these options:

![image](https://user-images.githubusercontent.com/2818394/101052847-28c17400-3598-11eb-806e-0facd1de82d0.png)

The second one will remove all phpDocs from your models(I hope you have git to restore everything if it will remove something important). And, as I remember you should choose Database in the first select.

**Comment by adelf** [comment] 2020-12-03 15:54
Also, there are some issues when `vendor` folder is marked as Excluded. I'll add this to the documentation soon.

**Comment by plweil** [comment] 2020-12-03 16:08
Ok, done. What I'm seeing now is that methods from both Eloquent Builder and the QueriesRelationships trait (mentioned above) are not being recognized (e.g., `join`, `where`, `whereRaw`, `doesntHave`). It flags the first instance of each of these in each method.

   "Method [name] not found in [modelName]".

Scopes, however, are recognized. The `vendor` folder is not Excluded, although most of the subdirectories within it are. A few months ago I was having issues with PHPStorm constantly indexing until I started excluding more directories.

**Comment by adelf** [comment] 2020-12-03 16:13
In my projects, it sees all these methods except `doesntHave`. Only `whereDoesntHave`. Excluding `vendor/laravel/framework` folder might be the reason for it. If not... there are bugs with some model names, like `Box`, `Fox`, etc. They already fixed and the new version will be released soon.

**Comment by plweil** [comment] 2020-12-03 16:36
Hmm, that seems a little odd. I've "unexcluded" `vendor/laravel/framework`, restarted, but still see no change. I don't think there's anything odd about my model names that should cause an issue; e.g., 'Alumnus', 'StudentPlacement'. I guess it's good to know that it *should* be working. I wonder whether there's anything else on my end that could be causing this. btw, I am running Laravel 6.18 (relatively old, I know, but team leadership is conservative ...) and PHPStorm 2020.2, MacOS 10.15.7. Maybe I should try updating to 2020.3.

**Comment by adelf** [comment] 2020-12-03 16:51
It won't help. 
If it is not difficult you can send me the model code and database table structure. I can try to reproduce the issue. It helped with `Box` model :)

P.S. I have a special unit test for `Alumnus` model name.
![image](https://user-images.githubusercontent.com/2818394/101060827-e05a8400-35a0-11eb-8c55-d8f4deb68439.png)
Is it correct?

**Comment by plweil** [comment] 2020-12-03 17:20
That's the correct table name. But wait...

I could be seeing things, but updating to 2020.3 appears to have fixed everything. (knock on wood!)

The only complaint I see now is about declaring $timestamps=false in one model.

    [model] and HasTimestamps define the same property timestamps

I'll see whether I can figure that one out. And hopefully nothing else will rear it's ugly head.

**Comment by adelf** [comment] 2020-12-03 17:24
Hm... Great! You'll definitely like the eloquent-related completions if everything generated correctly. Seems, PhpStorm should reindex everything after removing "Excluded" mark from folders.

**Comment by plweil** [comment] 2020-12-03 17:58
Out of curiosity, are you able to set

      public $timestamps = false;

in a model and not have PHPStorm flag it as an error?

**Comment by adelf** [comment] 2020-12-03 18:27
Yes. I also see this error. Seems, it's false positive for PhpStorm inspection. Strange that it doesn't show anything for other properties... There are connectivity problems with PhpStorm's bug tracker https://youtrack.jetbrains.com/. I'll try to find an issue about it there tomorrow.

**Comment by plweil** [comment] 2020-12-03 18:33
Thank goodness. That's good to hear. ;-)

And thanks for all of your excellent work and help on this.

**Comment by adelf** [comment] 2020-12-03 21:06
https://youtrack.jetbrains.com/issue/WI-56143
"the fix will be available in 2020.3.1."

**Comment by plweil** [comment] 2020-12-03 23:45
Great! That’s a quick response. Thanks.

Sent from my iPhone

On Dec 3, 2020, at 3:06 PM, Adel <notifications@github.com> wrote:

﻿

https://youtrack.jetbrains.com/issue/WI-56143
"the fix will be available in 2020.3.1."

**Comment by plweil** [comment] 2020-12-04 02:15
Just to circle back to the original issue: it's back. I have no idea why, but the methods from Eloquent Builder and the QueriesRelationships are getting flagged again, just as they were earlier today. It's primarily `join` and `where`, and even whereYearID in Alumnus, even though it is present in the _ide_helper file:

         * @method _AlumnusQueryBuilder whereYearId($value)

I invalidated the cache, reindexed, and re-ran the Eloquent Code Generator.
Evidently something has gone awry; maybe it will all be gone by tomorrow morning.

**Comment by adelf** [comment] 2020-12-04 05:58
It is not static. What option did you choose in the Generator dialog: User::where() or $user->where()?

**Comment by plweil** [comment] 2020-12-04 12:05
User::where()

I used the same options you asked me to try yesterday.

Sent from my iPhone

On Dec 3, 2020, at 11:59 PM, Adel <notifications@github.com> wrote:

﻿

It is not static. What option did you choose in the Generator dialog: User::where() or $user->where()?

**Comment by adelf** [comment] 2020-12-04 15:35
Could you send me _ide_helper_models.php file - support@laravel-idea.com? And it's location? vendor/_ide_helper_models.php?

**Comment by adelf** [comment] 2020-12-04 15:36
Also, there is a bug when these methods from helper file don't work inside the model class. 
https://youtrack.jetbrains.com/issue/WI-54460

**Comment by plweil** [comment] 2020-12-04 15:46
Sent.

**Comment by adelf** [comment] 2020-12-04 16:06
I just copied your file to my project, created `App\Models\Alumnus` class and:

![image](https://user-images.githubusercontent.com/2818394/101186117-b61dca80-3663-11eb-9fab-b07b4b03c358.png)

Of course, each method is completed.

**Comment by adelf** [comment] 2020-12-04 16:19
But it gives error inside the class:

![image](https://user-images.githubusercontent.com/2818394/101187595-9d161900-3665-11eb-8c30-8a27ce361f49.png)

It's a PhpStorm issue: https://youtrack.jetbrains.com/issue/WI-54460
I hope they will do something with it.

**Comment by plweil** [comment] 2020-12-04 16:27
Exactly. Here's what I see:

![Screen Shot 2020-12-04 at 10 23 58 AM](https://user-images.githubusercontent.com/1033771/101188268-189ea880-361b-11eb-8e10-53f4e15ece6d.png)

**Comment by adelf** [comment] 2020-12-04 16:30
Just vote here: https://youtrack.jetbrains.com/issue/WI-54460 :)

**Comment by plweil** [comment] 2020-12-04 18:19
Done!

**Comment by adelf** [comment] 2021-02-26 10:26
The new Eloquent Helper Generator from the 4.1.1 version allows pasting @mixin tags which fixes this issue.

**Closed by adelf** 2021-02-26 10:26 UTC
Labels: implemented - wait next release
