### ISSUE TITLE
Attached hotkeys resets on every plugin update

### ISSUE THREAD

**Issue by Insolita** [laravel-idea/plugin#62] opened 2020-05-26 11:38 UTC
Hi, I not completely sure, is it plugin's bug, or IDEA platform's bug. I reassign default hotkey for code generation, but it resets to default Ctrl+Shift+Comma after each plugin update

**Comment by adelf** [comment] 2020-05-26 11:55
Hi. I'm sure it's IDEA bug, because I only declare the default hotkey in the plugin... but when another plugin user reported about this, they said it can't be :) I'll try to find the real reason of the problem. Thank you.

P.S. I couldn't reproduce it in my local :(

**Comment by Insolita** [comment] 2020-05-28 18:45
I 've caught it at least twice, but for the first time is possible that phpstorm version was also updated.
Will keep this case in mind for the next plugin update

**Comment by adelf** [comment] 2020-05-31 08:17
no need on "keeping in mind" :) I know another user of plugin who has the same issue. I'll ask JetBrains guys...

**Comment by andrey-helldar** [comment] 2020-06-05 16:44
I don’t know if such a problem appears when installing the plugin from a file, but it definitely appears when updating the plugin using the standard method.

**Comment by adelf** [comment] 2020-08-24 19:01
@andrey-helldar updated to the 3.2.0.202 version without resetting hotkey. 
@Insolita could you also check?

**Comment by Insolita** [comment] 2020-09-08 05:34
yes, and now update to 3.3.x flush hotkey to ctrl+shift+comma again

**Comment by andrey-helldar** [comment] 2020-09-08 07:46
> yes, and now the update to 3.3.x resets hotkey to ctrl+shift+comma again

me too((

**Comment by Insolita** [comment] 2020-10-09 15:34
has reseted again :worried: :worried: :worried: 

![idea](https://user-images.githubusercontent.com/1847402/95602117-0a9f3200-0a87-11eb-81b4-745e194f5e2a.png)

Nova Resource support :fire: :fire: :fire:

**Comment by andrey-helldar** [comment] 2020-10-09 20:51
Me too...

**Comment by adelf** [comment] 2021-02-08 11:51
https://youtrack.jetbrains.com/issue/IJSDK-1011

**Comment by adelf** [comment] 2021-04-22 18:58
Info from @andrey-helldar: that was fixed in IntelliJ 2021.1 releases. So closing this for now. Reopen or comment if it will happen again.

**Closed by adelf** 2021-04-22 18:58 UTC
