### ISSUE TITLE
[Bug]: Autocompletion unavailable when extending a base Eloquent model

### ISSUE THREAD

**Issue by ZacharyDuBois** [laravel-idea/plugin#728] opened 2023-02-23 14:54 UTC
### Bug description

When extending a base Eloquent model (for example, when you have sets of models with all the same base traits, properties, etc), Laravel Idea recognizes it is a Laravel object, but does not provide autocompletion for it (casts, properties, etc).

### Plugin version

6.3.0.223

### Operating system

MacOS

### Steps to reproduce

1. Create a base class that extends the normal Eloquent model.

```php
abstract class BaseModel extends Model
{
    use HasUlids;
    use SoftDeletes;

    /**
     * @inheritdoc
     */
    protected $dateFormat = 'Y-m-d H:i:s.uO';
}
```

2. Create a class that extends your abstracted class.
```php
class Test extends BaseModel
{
    protected $attributes = [ // <-- Does not auto complete.
        'id'             => null,
        'name'           => null,
        'created_at'     => null,
        'updated_at'     => null,
        'deleted_at'     => null,
    ];
    protected $fillable   = [ // <-- Does not auto complete.
        'name',
    ];
    protected $hidden     = [];
    protected $casts      = [ // <-- Does not auto complete.
        'id'             => 'string',
        'test'           => 'string', 
        'created_at'     => 'datetime',
        'updated_at'     => 'datetime',
        'deleted_at'     => 'datetime',
    ];
}
```

**Comment by adelf** [comment] 2023-03-01 16:04
Hi, I couldn't reproduce this(it worked for me), but I'm aware of this bug. It depends on something else, and I still can't find a reason.

Closing this as a duplicate of #657

**Closed as completed by adelf** 2023-03-01 16:04 UTC
