### ISSUE TITLE
Shortcut doesn't persist

### ISSUE THREAD

**Issue by ninthspace** [laravel-idea/plugin#203] opened 2021-02-08 11:09 UTC
I don't know if this is an issue with the JetBrains plugin system, or this plugin in particular, but every time I update the plugin, the shortcut that invokes the plugin reverts to the default.

PhpStorm 2021.1 EAP
Build #PS-211.5538.21, built on February 5, 2021
PhpStorm EAP User
Expiration date: March 7, 2021
Runtime version: 11.0.10+8-b1304.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-65-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Non-Bundled Plugins: org.intellij.plugins.postcss (211.5538.10), org.jetbrains.plugins.stylus (211.5538.13), com.kalessil.phpStorm.phpInspectionsEA (4.0.6), dev.nybroe.collector (0.3.2), ru.adelf.idea.dotenv (2021.1), com.laravel_idea.plugin (3.6.2.211)
Current Desktop: zorin:GNOME

**Comment by adelf** [comment] 2021-02-08 11:51
Hi, Chris. Yes, it's an old problem. I think it's on IntelliJ's side. I've created an issue in their tracker: https://youtrack.jetbrains.com/issue/IJSDK-1011
Closing this one as duplicate of #62

**Closed by adelf** 2021-02-08 11:51 UTC
