### ISSUE TITLE
[Bug]: Livewire v2 components are not recognized after changing livewire path.

### ISSUE THREAD

**Issue by robert-stanciu** [laravel-idea/plugin#918] opened 2024-01-17 09:03 UTC
### Bug description

I have changed the Livewire `class_namespace` from `App\\Http\\Livewire` to `App\\Livewire` for migration purposes and now the <livewire:path.component-name/> suggestions are not working anymore.

![image](https://github.com/laravel-idea/plugin/assets/17193524/32b162a8-2c41-4301-8895-58af5f7128ec)

### Plugin version

8.0.2.233

### Operating system

MacOS

**Comment by adelf** [comment] 2024-01-17 09:40
Please change the namespace here, also. Sorry for the inconvenience. We will try to fetch this value right from Laravel config in the future.

<img width="883" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/f7bcb9fa-c1dd-41af-9dba-7262f0f7c64c">

**Comment by robert-stanciu** [comment] 2024-01-19 07:47
Hi, I am now facing a slightly different issue. The go-to view does not work anymore for any views.

e.g.
From the component to the view works fine:
![image](https://github.com/laravel-idea/plugin/assets/17193524/05580fc5-09a5-45f2-ae5b-da5836b07f32)

From the view back to the component it's now broken:
![image](https://github.com/laravel-idea/plugin/assets/17193524/78eaa539-1144-44e5-ad9d-dae4a2e6b749)

**Comment by adelf** [comment] 2024-01-21 10:19
It should be fixed by 8.0.4 release. Please update. The problem is not related to this. We moved the Find View Usages to the right click > Go To > View Usages action. But users asked to return the Usages line marker back.

**Closed as completed** 2024-01-23 17:29 UTC
