### ISSUE TITLE
[Bug]: rules() not auto complete if class extend a child of FormRequest

### ISSUE THREAD

**Issue by SocolaDaiCa** [laravel-idea/plugin#723] opened 2023-02-18 13:35 UTC
### Bug description

![image](https://user-images.githubusercontent.com/18243451/219868633-44216d08-ae3a-4b7a-ba09-a0158481d825.png)

### Plugin version

6.2.5.223

### Operating system

Windows

### Steps to reproduce

- make request Abc\StoreRequest
- make request Abc\IndexRequest
- request Abc\IndexRequest extends make request Abc\StoreRequest

**Comment by adelf** [comment] 2023-02-22 07:16
Hello. I couldn't reproduce this bug. However, there is an issue with completing these rules, which is hard to catch.
Let me close this since there is a #544 - the same issue.

**Closed as not planned by adelf** 2023-02-22 07:16 UTC

**Comment by SocolaDaiCa** [comment] 2023-02-22 08:03
@adelf I think these are 2 completely different errors

My error occurs when the class does not directly extend FormRequest

**Comment by adelf** [comment] 2023-02-22 08:08
I tried three levels of inheritance - everything worked.

**Comment by SocolaDaiCa** [comment] 2023-02-22 08:21
@adelf Could you take a photo demo?

**Comment by adelf** [comment] 2023-02-22 08:24
<img width="224" alt="image" src="https://user-images.githubusercontent.com/2818394/220563401-d3a0967c-e07a-4ab5-a9c2-fb13ba60b851.png">

This bug is floating. It's tough to catch. But I'll try to find it somehow today.

**Comment by SocolaDaiCa** [comment] 2023-02-22 08:32
@adelf Oh, I see

It only work in `Standard application` (`app/Http/Requests`), but not work in Moldule system `nwidart/laravel-modules paclage`

![image](https://user-images.githubusercontent.com/18243451/220565170-5995e690-55a8-42f6-a202-68c37d593afc.png)

Please help to check in mode Moldule system `nwidart/laravel-modules paclage`

**Comment by adelf** [comment] 2023-02-22 08:36
The same: it works.

<img  alt="image" src="https://user-images.githubusercontent.com/2818394/220566299-af0eed52-c633-467a-b090-988255399d97.png">

**Comment by SocolaDaiCa** [comment] 2023-02-22 08:42
@adelf Are you create request inside folder Modules?

try to create request inside Modules folder: 
namespaces: `Modules\PackageA\Http/Requests`

- `Modules/package-a/src/Http/Requests/FooRequest`
- `Modules/package-a/src/Http/Requests/BarRequest`
- `BarRequest` extends `FooRequest`

error will occur, and It only occur inslide Modules folder

If you can't reproduce, I will create a demo project

**Comment by adelf** [comment] 2023-02-22 08:55
Sorry, I forgot to show that the last request was in the `Modules\Test1\Http\Requests` namespace. You can try to create a project, but I'm sure I couldn't reproduce it either.
