### ISSUE TITLE
[Bug]: toArray() not found after upgrading to Laravel 11

### ISSUE THREAD

**Issue by ryanmortier** [laravel-idea/plugin#1046] opened 2024-08-01 17:55 UTC
### Bug description

I think this is due to upgrading to Laravel 11 but not 100% sure. I do know that prior to upgrading, this was not warning.

`App\Models\Crm\Collection` extends `Illuminate\Database\Eloquent\Model` which has the `toArray` method. I'm not sure why this is showing up.

![CleanShot 2024-08-01 at 13 54 13](https://github.com/user-attachments/assets/2c93e83d-3f30-4317-a70c-1a761f7bbbda)

### Plugin version

v8.2.2.241

### Operating system

MacOS

**Comment by xHeaven** [comment] 2024-08-03 20:13
This needs more attention, it happens all over our codebase as well. For us, it didn't happen _directly_ after moving to Laravel 11, but in the last couple weeks. I'm assuming some Laravel update broke things. Unfortunately, this made Laravel Idea almost unusable for Models (without explicitly type-hinting them in a variable).

![image](https://github.com/user-attachments/assets/4ebbe2f8-3742-4690-af8e-7069ac1ad370)
![image](https://github.com/user-attachments/assets/94327486-4097-435f-8701-2040b500cfe4)
![image](https://github.com/user-attachments/assets/b12bf4d3-301c-4952-bd68-fff6a86f91dc)
![image](https://github.com/user-attachments/assets/20282616-a44b-4a9b-b800-c9f1ab352b18)

**Comment by adelf** [comment] 2024-08-04 09:50
It's caused by Laravel 11.17 update. The fix will be released next week.

**Comment by xHeaven** [comment] 2024-08-04 18:24
> It's caused by Laravel 11.17 update. The fix will be released next week.

Thanks a lot @adelf, we really appreciate it! Keep up the good work!

**Comment by adelf** [comment] 2024-08-11 16:55
Fixed in the 8.2.3.

**Closed as completed by adelf** 2024-08-11 16:55 UTC
Labels: implemented - wait next release
