### ISSUE TITLE
[Feature improvement / bug] Policy autocompletion works, but jump to definition does not.

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#220] opened 2021-02-24 10:21 UTC
This is related to #92 

Autocompletion of available policy methods works as expected, but jumping to definition does not (when the second argument is a model instance).

Controller example:
```php
public function show(Post $post)
{
    // Autocompletion works, but jump to definition does not.
    $this->authorize('view', $post);
}

public function store(Request $request)
{
    // Both autocompletion and jump to definition works
    $this->authorize('create', Post::class);
}
```

**Comment by adelf** [comment] 2021-02-24 20:51
Can't reproduce this. Everything works... Maybe you missed this method in PostPolicy? Because I have to complete all possible policies is there is no second parameter yet.
![image](https://user-images.githubusercontent.com/2818394/109064084-ff2d6a00-76fa-11eb-95a0-248f6663f19f.png)

**Comment by adelf** [comment] 2021-02-26 09:23
Closing this one. Please comment here if there are still some issues with it.

**Closed by adelf** 2021-02-26 09:23 UTC
